pipeline 
{
  agent any
  environment 
  {
    registry = "guevavil/webservice-maven"
  }
  stages 
  {
    stage('Builds') 
    {
      agent 
      {
        docker 
        {
          image 'maven:3.6.3-jdk-8' 
          args '-v /root/.m2:/root/.m2' 
        }
      }
      steps 
      {
        sh 'mvn clean install' 
      }
    }
    stage('Publish') 
    {
      agent any
      environment 
      {
        registryCredential = 'dockerhub'
        dockerImage = ''
      }
      steps 
      {
        echo '=== Publish Maven Docker Image ==='
        sh 'mv devops/Dockerfile .'
        script 
        {
          dockerImage = docker.build registry + ":$BUILD_NUMBER"
          docker.withRegistry( '', registryCredential ) 
          {
            dockerImage.push()
          }
        }
      }
    }
    stage ('Deploy') 
    {           
      steps 
      {
        echo '=== Deploy Maven Docker Image ==='
        sh 'mv devops/replace-yaml.py .'
        sh 'mv devops/ingress-deployment.yaml .'     
        script
        {                   
          def image_id = registry + ":$BUILD_NUMBER"
          def commit = sh(returnStdout: true, script: 'git log -1 --oneline').trim()          
          sh "python replace-yaml.py \"${commit}\" \"${image_id}\""
          sh "/usr/local/bin/kubectl config use-context jenkins"
          sh "/usr/local/bin/kubectl apply -f ingress-deployment.yaml -n ingress-nginx"             
        }           
      }       
    }   
  }
}