pipeline 
{
  agent any
  environment 
  {
    registry = "guevavil/webservice-maven"
  }
  stages 
  {
    stage('Builds') 
    {
      agent 
      {
        docker 
        {
          image 'maven:3.6.3-jdk-8' 
          args '-v /root/.m2:/root/.m2' 
        }
      }
      steps 
      {
        sh 'mvn clean install' 
      }
    }
    stage('Publish') 
    {
      agent any
      environment 
      {
        registryCredential = 'dockerhub'
        dockerImage = ''
      }
      steps 
      {
        echo '=== Publish Maven Docker Image ==='
        sh 'mv devops/Dockerfile .'
        script 
        {
          dockerImage = docker.build registry + ":$BUILD_NUMBER"
          docker.withRegistry( '', registryCredential ) 
          {
            dockerImage.push()
          }
        }
      }
    }
    stage ('Deploy') 
    {           
      steps 
      {
        echo '=== Deploy Maven Docker Image ==='
        sh 'mv devops/playbook.yaml .'     
        script
        {                   
          def image_id = registry + ":$BUILD_NUMBER"                   
          sh "ansible-playbook  playbook.yaml --extra-vars \"image_id=${image_id}\""               
        }           
      }       
    }   
  }
}